### ISSUE TITLE
Would you be ok with this control being added to the UI Extensions project?

### ISSUE THREAD

**Issue by SimonDarksideJ** [ryanslikesocool/Unity-Card-UI#1]
We'd love to see this control added to the extensive UI Extensions project, which packages up great UI controls for Unity in one project.
Full contributions to the authors are retained.

Let us know!
https://bitbucket.org/UnityUIExtensions/unity-ui-extensions/src/master/

**Comment by ryanslikesocool** [comment]
I'd be honored!  Is there anything that I need to do to make that happen?

**Comment by SimonDarksideJ** [comment]
If you can can generate a PR to add the control / code plus some documentation, that would be great.
Else I can just grab it and pull it in :D

**Comment by ryanslikesocool** [comment]
It's taken me _way_ too long for me to get around to doing this.  I tried using BitBucket to fork and create a PR but it's proven to be too difficult for an idiot like me (git is scary!).  😓  There's really nothing to document since it's all in code comments and on the cards themselves.  I'd really appreciate it if you could just grab and pull it in like you offered.

**Comment by SimonDarksideJ** [comment]
I was planning on grabbing it :D, hopefully will get to this in the next week or so as it's next on my list.  Thanks for the great work and agreeing to contribute.
